# Selecting Core
CORTEX_M=4
CORE=CM$(CORTEX_M)

# Compiler & Linker
CC=arm-none-eabi-gcc
CXX=arm-none-eabi-g++

# Options for specific architecture
ARCH_FLAGS=-mthumb -mcpu=cortex-m$(CORTEX_M)

# -Os -flto -ffunction-sections -fdata-sections to compile for code size
CFLAGS=$(ARCH_FLAGS) $(STARTUP_DEFS) -Os -flto -ffunction-sections -fdata-sections -T link.ld
CXXFLAGS=$(CFLAGS)

# Create map file
MAP=-Wl,-Map=$(NAME).map
